Track access count in binary-search
exercism/coffeescript pull request #362
Opened 2024-11-09 18:50 UTC by BNAndras

Inspired by https://github.com/exercism/lua/blob/main/exercises/practice/binary-search/TracedArray.lua, this proposed change tracks how often the input values are accessed so a binary search algorithm must be implemented.

This is a `maintained-autonomous` repo so no review is needed, but I'd like to get a second set of eyeballs so I'm pinging @exercism/cross-track-maintainers.

2024-11-09 19:29 UTC, glennj requested changes

2024-11-09 19:29 UTC, glennj commented on exercises/practice/binary-search/binary-search.coffee
This is probably the example content, yes?

2024-11-09 19:46 UTC, BNAndras commented on exercises/practice/binary-search/binary-search.coffee
Oops, fixed.

2024-11-09 23:32 UTC, glennj commented on exercises/practice/binary-search/traced-array.coffee
You'll need to add this file to the .meta/config.json in .files.editor array so that it shows up online.

2024-11-10 00:12 UTC, SleeplessByte approved these changes

2024-11-10 00:12 UTC, SleeplessByte commented on exercises/practice/binary-search/traced-array.coffee
(unless you don't want it to show up)

2024-11-10 02:55 UTC, glennj approved these changes

2024-11-10 03:45 UTC, merged

2024-11-10 03:45 UTC, BNAndras commented
Thanks all! :)